import Head from "next/head";
import Cards from "@/components/Cards/Cards";
import Pagination from "@/components/Pagination/Pagination";
import { useEffect, useState } from "react";
import Loader from "@/components/Loader/Loader";
import { api } from "@/utils/Api";

export default function Home() {
  const [paginationState, setPaginationState] = useState({
    page: 1,
    limit: 4,
  });
  const [loading, setLoading] = useState(true);
  const [cards, setCards] = useState([]);

  const getCards = (pageNumber) => {
    setLoading(true);
    api.getInitialCards(pageNumber).then((data) => {
      setCards(data);
      setLoading(false);
    });
  };

  useEffect(() => {
    getCards(paginationState.page);
  }, [paginationState.page]);

  return (
    <>
      <Head>
        <title>Cards</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {loading ? (
          <Loader />
        ) : (
          <div>
            <Cards cards={cards} />
            <Pagination
              paginationState={paginationState}
              setPaginationState={setPaginationState}
            />
          </div>
        )}
      </main>
    </>
  );
}
